# Generated by Django 6.0.3 on 2026-03-16 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('job_description', models.TextField()),
                ('job_description_url', models.URLField(blank=True)),
                ('content', models.JSONField(default=dict)),
                ('template_snapshot', models.TextField(blank=True, help_text='Snapshot of template HTML when CV was generated')),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('match_score', models.IntegerField(default=0)),
                ('keywords_matched', models.JSONField(blank=True, default=list)),
                ('missing_keywords', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('rejected', 'Rejected'), ('offer', 'Offer Received')], default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='profiles.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cvs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('application_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='applied', max_length=50)),
                ('response_received', models.BooleanField(default=False)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='cvs.cv')),
            ],
            options={
                'db_table': 'cv_applications',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/')),
                ('html_file', models.FileField(help_text='Upload HTML template file', upload_to='templates/html/')),
                ('css_file', models.FileField(blank=True, help_text='Optional CSS file', null=True, upload_to='templates/css/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/previews/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True, help_text='Public templates are available to all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cv',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The template used for this CV', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvs', to='cvs.template'),
        ),
        migrations.CreateModel(
            name='CVVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('content', models.JSONField(default=dict)),
                ('changes_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cvs.cv')),
            ],
            options={
                'db_table': 'cv_versions',
                'ordering': ['-version_number'],
                'unique_together': {('cv', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='cvs.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_templates',
                'unique_together': {('user', 'template')},
            },
        ),
    ]
