# Generated by Django 6.0.3 on 2026-03-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='template_binary_path',
            field=models.CharField(blank=True, help_text='Path to generated binary file (for DOCX/PDF templates)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='docx_file',
            field=models.FileField(blank=True, help_text='Upload Word template file', null=True, upload_to='templates/docx/'),
        ),
        migrations.AddField(
            model_name='template',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF template file', null=True, upload_to='templates/pdf/'),
        ),
        migrations.AddField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('html', 'HTML/CSS'), ('docx', 'Microsoft Word'), ('pdf', 'PDF Form')], default='html', max_length=10),
        ),
        migrations.AlterField(
            model_name='cv',
            name='template_snapshot',
            field=models.TextField(blank=True, default='', help_text='Snapshot of template HTML when CV was generated (for HTML templates only)', null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='css_file',
            field=models.FileField(blank=True, help_text='Optional CSS file for HTML templates', null=True, upload_to='templates/css/'),
        ),
        migrations.AlterField(
            model_name='template',
            name='html_file',
            field=models.FileField(blank=True, help_text='Upload HTML template file', null=True, upload_to='templates/html/'),
        ),
    ]
